version: "3"

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/prueba
      - APPLICATION_NAME=Share Your Idea(SYI)
      - JWT_SECRET=MY_SECRETE_AHH
      - CACHE_KEY=MI_CACHE_KEY_AHH
      - SWAGGER_DOC=swaggerDEV
    ports:
      - "5000:5000"

  mongo:
    image: mongo
